# Gitleaks Configuration for Children of Singularity
# This file defines rules for detecting secrets and credentials in commits

title = "Children of Singularity - Gitleaks Configuration"

[extend]
# Use the default gitleaks rules as a base
useDefault = true

# Custom rules for this project
[[rules]]
id = "database-url"
description = "PostgreSQL database URL"
regex = '''(postgresql|postgres):\/\/[a-zA-Z0-9._-]+:[a-zA-Z0-9._-]+@[a-zA-Z0-9._-]+:\d+\/[a-zA-Z0-9._-]+'''
tags = ["database", "postgresql"]

[[rules]]
id = "fastapi-secret-key"
description = "FastAPI secret key"
regex = '''(?i)(secret_key|SECRET_KEY)\s*[=:]\s*["\']([a-zA-Z0-9._-]{16,})["\']'''
tags = ["fastapi", "secret", "key"]

[[rules]]
id = "jwt-secret"
description = "JWT secret key"
regex = '''(?i)(jwt_secret|JWT_SECRET|jwt_key|JWT_KEY)\s*[=:]\s*["\']([a-zA-Z0-9._-]{16,})["\']'''
tags = ["jwt", "secret", "authentication"]

[[rules]]
id = "openai-api-key"
description = "OpenAI API key"
regex = '''sk-[a-zA-Z0-9]{48}'''
tags = ["openai", "api", "key"]

[[rules]]
id = "generic-api-key"
description = "Generic API key pattern"
regex = '''(?i)(api_key|API_KEY|apikey|APIKEY)\s*[=:]\s*["\']([a-zA-Z0-9._-]{16,})["\']'''
tags = ["api", "key", "generic"]

[[rules]]
id = "private-key"
description = "Private key"
regex = '''-----BEGIN [A-Z ]+ PRIVATE KEY-----'''
tags = ["private", "key", "crypto"]

[[rules]]
id = "godot-encryption-key"
description = "Godot encryption key"
regex = '''(?i)(encryption_key|ENCRYPTION_KEY|crypt_key|CRYPT_KEY)\s*[=:]\s*["\']([a-zA-Z0-9._-]{16,})["\']'''
tags = ["godot", "encryption", "key"]

# File patterns to ignore (allowlist for false positives only)
[allowlist]
description = "Allowlist for false positives and safe files only"
files = [
    '''\.git/.*''',
    '''\.gitleaks\.toml''',
    '''backend/venv/.*''',
    '''logs/.*''',
    '''\.log$''',
    '''README\.md$''',
    '''memory_bank/.*''',
    '''documentation/.*''',
    '''_docs/.*''',
    '''\.godot/.*''',
    '''\.import$''',
    '''\.tmp$''',
    '''\.rdb$''',
    '''\.dmp$''',
    '''project\.godot$''',
]

# SAFE patterns for specific test/example contexts only
# Only add patterns here that are genuinely safe (test files, documentation examples)
regexes = [
    # Only ignore secrets in obvious test/example/placeholder contexts
    '''(?i)(example|placeholder|dummy|test|sample).*secret.*''',
    '''(?i)(example|placeholder|dummy|test|sample).*key.*''',
    '''(?i)(example|placeholder|dummy|test|sample).*password.*''',
]

# Specific paths for safe files only - be very conservative here
paths = [
    '''.*_test\.py$''',
    '''.*_test\.gd$''',
    '''test_.*\.py$''',
    '''test_.*\.gd$''',
    '''.*\.sample$''',
    '''.*\.example$''',
    '''.*\.template$''',
    '''.*\.md$''',
    '''documentation/.*''',
    '''_docs/.*''',
    '''memory_bank/.*''',
    # Schema files should be checked for embedded secrets
    # Only exclude if they contain no sensitive data
    '''data/postgres/schema\.sql$''',
]

# Entropy detection settings
[entropy]
# Enable entropy detection for high-entropy strings
enable = true
# Minimum entropy threshold (0.0 - 8.0)
threshold = 4.0
# Groups to check for entropy
groups = ["password", "key", "secret", "token", "api", "jwt"]
